### ISSUE TITLE
Number allocation failed

### ISSUE THREAD

**Issue by iamheisenberg23** [cjdrumm/text-plus-poc#1]
Hello, I am getting this error while allocating text-plus number

NPTN Allocation is not allowed.

Please help.

![image](https://user-images.githubusercontent.com/48607132/56685643-114db400-66f0-11e9-9898-fd1b99a19059.png)

**Comment by cjdrumm** [comment]
Hello, NPTN allocation error accures when textplus trys to allocate a number for your account but all numbers with the area code are already in use (this happened because i hardcoded the localeId into header).
This error isn't fatal, and your account will be assigned a "default" number. In the app you are able to select an area code see: https://github.com/cjdrumm/text-plus-poc/blob/master/textplus.py#L140. The "localeId" is what is used to assign you a number provided an area code. I.E say you want a 916 number? localeId could be: "2131n1312313yoiuohi3", NTPN happens when all 916 numbers have been allocated. I will fix this in a later update and put "areaCode" in the prefs.json file so you can try and get a number with a specific area code.
